### ISSUE TITLE
Проблема с сетью

### ISSUE THREAD

**Issue by NikolayKorotkikh** [Dirilean/Road#3]
При остановке  сервера, Unity останавливается. Начинает продолжать работать только при фокусировке на сам Unity (в любой области).

**Comment by Dirilean** [comment]
то есть только тогда, когда окно unity активно?

**Comment by NikolayKorotkikh** [comment]
Я на Python останавливаю сервер, в Unity "машинка" перестает двигаться, нажимаю на окно Unity и продолжает свое движение

**Comment by NikolayKorotkikh** [comment]
Оказывается, что перестает все двигаться, не когда сервер останавливаешь, а просто когда фокус с unity убрал

**Comment by Dirilean** [comment]
я думаю это проблема того, что мы сейчас работаем в редакторе, и если мы будем юзать конечный экзешник такого не будет, но все от ОС зависит ядумаю.. от того как она активные окна и неактивные отображает

**Comment by NikolayKorotkikh** [comment]
мб, ща проверю на экзешнеке

**Comment by NikolayKorotkikh** [comment]
всё огонь.починилось
