### ISSUE TITLE
Неправильно считает количество людей

### ISSUE THREAD

**Issue by NikolayKorotkikh** [Dirilean/Road#8]
Данные переданные на сервер: 
![31897187-05d29a08-b82f-11e7-8776-0be612bea300](https://user-images.githubusercontent.com/32987605/31897381-a4b2bd88-b82f-11e7-9f57-41a5dc483573.png)
Сцена в Unity: 
![default](https://user-images.githubusercontent.com/32987605/31897290-5320e972-b82f-11e7-9d26-cb031a746c42.png)
Когда человек идет по зебре, то отображается, что его нет, что не совсем верно. Надо обдумать как правильно колайдеры поставить.

**Comment by Dirilean** [comment]
то есть нужно обязательно чтобы он считал и на пешеходнике? мне кажется это неправильно. тк светофор все равно переключится через минимум 15 сек или сколько там, все люди успеют перейти

**Comment by NikolayKorotkikh** [comment]
оки
