### ISSUE TITLE
Проблема с пушем!

### ISSUE THREAD

**Issue by Dirilean** [Dirilean/Road#9]
![image](https://user-images.githubusercontent.com/31008695/31903181-d318dd5e-b840-11e7-9874-4f2e174bea6e.png)
у нас с тобой конфликт в файлах, и я не знаю что с ним делать

**Comment by NikolayKorotkikh** [comment]
ееееее
Создай  ветку и туда, я там много чего наворотил

**Comment by Dirilean** [comment]
вроде разрешилась беда
